### ISSUE TITLE
Install from source

### ISSUE THREAD

**Issue by juanmirocks** [Rostlab/MetaDisorder#3]
The system appears to work perfectly fine. HOWEVER you are actually installing from the debian package, and not from this repository source, as required.

Did you try that?

**Comment by juanmirocks** [comment]
@iremu thanks for informing me about tomorrow.

Note that this is the most important remaining issue. The tool must be installable from the source.

**Comment by juanmirocks** [comment]
As indicated, I don't see instructions how to install from source.

**Comment by fsblu** [comment]
Hello,
We will provide it this week. For that, we need to uninstall everything and
try it again on our computer and see the extra errors we face. As it is
though, you should clone the code to your home directory and try to run it
there. There should not be anything more to do. At least that is what I can
tell for the errors I fixed.

Regards

2016-02-16 16:40 GMT+01:00 Juan Miguel Cejuela notifications@github.com:

> As indicated, I don't see instructions how to install from source.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Rostlab/MetaDisorder/issues/3#issuecomment-184736114.

## 

---

İrem Uygur

GSM:  (+49) 01575 684 25 74
           (+90) 537484 04 71

Skype:irem.uygur
G-mail: iremuygur1@gmail.com

**Comment by juanmirocks** [comment]
Sure but just write now in the readme how to install it or which script I
should try to run. I can also help by reporting the errors I face

**Comment by fsblu** [comment]
Hello,

1) I have updated README. Now, you can also see training set and evaluation
parts. @Sirma you may wanna look at that.
2) When I removed the package installation from my computer, the program
dies at the same point, when I run from the code. Which is line 703 runMD.
3) Do not remove the bin folder of the psipred. Psipred should be
individually compiled. The proram also asks for the bin of disopred which
was not there. I added it in to the bin.
4) I have sent a screen shot of the errors I receive, I think there is not
any change on my window. All errors are caused by input, output, not
generated files, which also can not be removed etc.

Irem

2016-02-18 12:19 GMT+01:00 Juan Miguel Cejuela notifications@github.com:

> Sure but just write now in the readme how to install it or which script I
> should try to run. I can also help by reporting the errors I face
> On Thu, 18 Feb 2016 at 11:25, irem uygur notifications@github.com wrote:
> 
> > Hello,
> > We will provide it this week. For that, we need to uninstall everything
> > and
> > try it again on our computer and see the extra errors we face. As it is
> > though, you should clone the code to your home directory and try to run
> > it
> > there. There should not be anything more to do. At least that is what I
> > can
> > tell for the errors I fixed.
> > 
> > Regards
> > 
> > 2016-02-16 16:40 GMT+01:00 Juan Miguel Cejuela <notifications@github.com
> > :
> > 
> > > As indicated, I don't see instructions how to install from source.
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> > > https://github.com/Rostlab/MetaDisorder/issues/3#issuecomment-184736114
> > > .
> > 
> > ## 
> > 
> > ---
> > 
> > İrem Uygur
> > 
> > GSM: (+49) 01575 684 25 74
> > (+90) 537484 04 71
> > 
> > Skype:irem.uygur
> > G-mail: iremuygur1@gmail.com
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/Rostlab/MetaDisorder/issues/3#issuecomment-185642506
> > .
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Rostlab/MetaDisorder/issues/3#issuecomment-185668641.

## 

---

İrem Uygur

GSM:  (+49) 01575 684 25 74
           (+90) 537484 04 71

Skype:irem.uygur
G-mail: iremuygur1@gmail.com

**Comment by juanmirocks** [comment]
@iremu Thanks Irem -- But I still see no instructions on how to install from source?

At this point, I realize it's gonna be impossible to have everything running perfectly. That's OK. At least we know the state of the project and and you did a great job.

Nonetheless, please still write the installation instructions so that I can reproduce your errors

**Comment by fsblu** [comment]
[image: Satır içi resim 1]  I have this part?

2016-02-22 10:58 GMT+01:00 Juan Miguel Cejuela notifications@github.com:

> @iremu https://github.com/iremu Thanks Irem -- But I still see no
> instructions on how to install from source?
> 
> At this point, I realize it's gonna be impossible to have everything
> running perfectly. That's OK. At least we know the state of the project and
> and you did a great job.
> 
> Nonetheless, please still write the installation instructions so that I
> can reproduce your errors
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Rostlab/MetaDisorder/issues/3#issuecomment-187103413.

## 

---

İrem Uygur

GSM:  (+49) 01575 684 25 74
           (+90) 537484 04 71

Skype:irem.uygur
G-mail: iremuygur1@gmail.com

**Comment by juanmirocks** [comment]
Sorry just checking now. Are we understanding each other? In both branches develop and MDCorrection I see how to install instructions, but they only refer to the apt-get instructions. I mean how to install it just from source instructions, as I know you did. But I don't see the instructions ?

**Comment by fsblu** [comment]
Can you check it now? I have carried installation from github to under the
debian package installation

2016-03-07 16:50 GMT+01:00 Juan Miguel Cejuela notifications@github.com:

> Sorry just checking now. Are we understanding each other? In both branches
> develop and MDCorrection I see how to install instructions, but they only
> refer to the apt-get instructions. I mean how to install it just from
> source instructions, as I know you did. But I don't see the instructions ?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Rostlab/MetaDisorder/issues/3#issuecomment-193309350.

## 

---

İrem Uygur

GSM:  (+49) 01575 684 25 74
           (+90) 537484 04 71

Skype:irem.uygur
G-mail: iremuygur1@gmail.com

**Comment by juanmirocks** [comment]
Now I see the instructions in the develop branch ( we will have to merge MDCorrections and develop). Do you also provide instructions for how to install "Blast, individual compilation of Psipred and the executable of Disopred are required for the package."  ?

**Comment by fsblu** [comment]
Updated. Can you please check it now?

2016-03-08 11:49 GMT+01:00 Juan Miguel Cejuela notifications@github.com:

> Now I see the instructions in the develop branch ( we will have to merge
> MDCorrections and develop). Do you also provide instructions for how to
> install "Blast, individual compilation of Psipred and the executable of
> Disopred are required for the package." ?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Rostlab/MetaDisorder/issues/3#issuecomment-193722765.

## 

---

İrem Uygur

GSM:  (+49) 01575 684 25 74
           (+90) 537484 04 71

Skype:irem.uygur
G-mail: iremuygur1@gmail.com

**Comment by juanmirocks** [comment]
Good I see. What about Disopred ?

**Comment by fsblu** [comment]
I have found disopred myself from internet, when I received an error asking
its executable. Unlike psipred, disopred can not be compiled with the
existing files in the project at least. So I put the binary there myself. I
did not want to write something like "install disopred yourself even though
you have files, they do not work.It also might be asking for a disopred
exectable with some changes to the one on internet. I do not know it. In
manpage it was stated that packages can not be compiled individually. "

2016-03-09 11:23 GMT+01:00 Juan Miguel Cejuela notifications@github.com:

> Good I see. What about Disopred ?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Rostlab/MetaDisorder/issues/3#issuecomment-194226505.

## 

---

İrem Uygur

GSM:  (+49) 01575 684 25 74
           (+90) 537484 04 71

Skype:irem.uygur
G-mail: iremuygur1@gmail.com

**Comment by juanmirocks** [comment]
OK, I'm been able to run it partially. At this point I think that will be enough.

I've also merged both branches develop & MDCorrections
